<a href="https://colab.research.google.com/github/jeffersondemota/AulasSenaiPython/blob/main/workend.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd

In [3]:
from google.colab import files
uploaded = files.upload()

Saving trabalho-introduction-to-data-analytics-QueryResult.xlsx to trabalho-introduction-to-data-analytics-QueryResult.xlsx

In [4]:
import io

In [5]:
dataset = list(uploaded.keys())[0]

In [6]:
data = uploaded[dataset]

In [7]:
df = pd.read_excel(io.BytesIO(data))

In [8]:
df.head()

,Data do Pedido,ID Pedido,Valor Pedido,Região,Total Itens Entregues,Volume Não Entregue,Hora da Entrega,ID Entregador,Nome Motorista,Idade Motorista,Viagens,ID Consumidor,Nome Clinte,Idade Cliente,product_id,Nome Produto,Categoria,Preco
0,2023-06-11,00005d78-6f97-4699-a746-19826f415e38,367.63,Sanford,18,0,15:00:45,WDID10017,Robert Reese,18,70,WCID5733,Joseph Perry,61,NaN,NaN,NaN,NaN
1,2023-07-08,0001dc8e-f58f-45ed-8bf2-5c820c9a30d7,419.80,Apopka,19,0,18:11:41,WDID10335,William Alexander,23,60,WCID6162,Christopher Green,77,NaN,NaN,NaN,NaN
2,2023-05-12,00026f89-7729-43b4-8b37-5185bd77d157,330.73,Clermont,14,0,18:26:19,WDID09977,Troy Garcia,18,27,WCID6169,Kevin Reyes,77,NaN,NaN,NaN,NaN
3,2023-11-26,000b9069-e507-406a-8586-d0c005afb71f,157.04,Apopka,10,0,19:46:32,WDID10728,Alan Johnson,48,75,WCID6139,Jacob Scott,37,NaN,NaN,NaN,NaN
4,2023-12-13,000c7595-7278-4b67-93be-f7eb02c81f3c,287.97,Clermont,3,0,20:12:43,WDID10353,Mr. Michael Brown,23,58,WCID5342,Gregory Flores,26,NaN,NaN,NaN,NaN

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13002 entries, 0 to 13001
Data columns (total 18 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Data do Pedido         13002 non-null  object
 1   ID Pedido              13002 non-null  object
 2   Valor Pedido           13002 non-null  float64
 3   Região                 13002 non-null  object
 4   Total Itens Entregues  13002 non-null  int64
 5   Volume Não Entregue    13002 non-null  int64
 6   Hora da Entrega        13002 non-null  object
 7   ID Entregador          13002 non-null  object
 8   Nome Motorista         13002 non-null  object
 9   Idade Motorista        13002 non-null  int64
 10  Viagens                13002 non-null  int64
 11  ID Consumidor          13002 non-null  object
 12  Nome Clinte            13002 non-null  object
 13  Idade Cliente          13002 non-null  int64
 14  product_id             1662 non-null   object
 15  Nome Produto           1662 non-null   object
 16  Categoria              1662 non-null   object
 17  Preco                  1662 non-null   float64
dtypes: float64(2), int64(5), object(11)
memory usage: 1.8+ MB

In [10]:
df.describe()

,Valor Pedido,Total Itens Entregues,Volume Não Entregue,Idade Motorista,Viagens,Idade Cliente,Preco
count,13002.000000,13002.000000,13002.000000,13002.000000,13002.000000,13002.000000,1662.000000
mean,297.380183,9.972927,0.382172,34.936010,45.419397,54.266421,89.875217
std,202.540864,5.479447,0.559648,15.524684,19.431296,20.975537,201.186840
min,20.080000,1.000000,0.000000,18.000000,11.000000,18.000000,2.160000
25%,149.895000,5.000000,0.000000,20.000000,29.000000,36.000000,8.210000
50%,277.380000,10.000000,0.000000,31.000000,45.000000,55.000000,12.530000
75%,403.457500,15.000000,1.000000,49.000000,63.000000,73.000000,18.350000
max,1386.000000,19.000000,3.000000,65.000000,78.000000,90.000000,908.870000

In [11]:
df_filtro_1 = df[df['Volume Não Entregue'] != 0]

In [12]:
df_filtro_1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4504 entries, 6 to 12998
Data columns (total 18 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Data do Pedido         4504 non-null   object
 1   ID Pedido              4504 non-null   object
 2   Valor Pedido           4504 non-null   float64
 3   Região                 4504 non-null   object
 4   Total Itens Entregues  4504 non-null   int64
 5   Volume Não Entregue    4504 non-null   int64
 6   Hora da Entrega        4504 non-null   object
 7   ID Entregador          4504 non-null   object
 8   Nome Motorista         4504 non-null   object
 9   Idade Motorista        4504 non-null   int64
 10  Viagens                4504 non-null   int64
 11  ID Consumidor          4504 non-null   object
 12  Nome Clinte            4504 non-null   object
 13  Idade Cliente          4504 non-null   int64
 14  product_id             1662 non-null   object
 15  Nome Produto           1662 non-null   object
 16  Categoria              1662 non-null   object
 17  Preco                  1662 non-null   float64
dtypes: float64(2), int64(5), object(11)
memory usage: 668.6+ KB

In [13]:
df_filtro_1 = df_filtro_1.dropna(subset=['product_id'])

In [14]:
df_filtro_1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1662 entries, 6 to 12996
Data columns (total 18 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Data do Pedido         1662 non-null   object
 1   ID Pedido              1662 non-null   object
 2   Valor Pedido           1662 non-null   float64
 3   Região                 1662 non-null   object
 4   Total Itens Entregues  1662 non-null   int64
 5   Volume Não Entregue    1662 non-null   int64
 6   Hora da Entrega        1662 non-null   object
 7   ID Entregador          1662 non-null   object
 8   Nome Motorista         1662 non-null   object
 9   Idade Motorista        1662 non-null   int64
 10  Viagens                1662 non-null   int64
 11  ID Consumidor          1662 non-null   object
 12  Nome Clinte            1662 non-null   object
 13  Idade Cliente          1662 non-null   int64
 14  product_id             1662 non-null   object
 15  Nome Produto           1662 non-null   object
 16  Categoria              1662 non-null   object
 17  Preco                  1662 non-null   float64
dtypes: float64(2), int64(5), object(11)
memory usage: 246.7+ KB

In [15]:
df_filtro_1.to_excel('df_filtro_1.xlsx', index=False)
files.download('df_filtro_1.xlsx')

In [16]:
df_filtro_1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1662 entries, 6 to 12996
Data columns (total 18 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Data do Pedido         1662 non-null   object
 1   ID Pedido              1662 non-null   object
 2   Valor Pedido           1662 non-null   float64
 3   Região                 1662 non-null   object
 4   Total Itens Entregues  1662 non-null   int64
 5   Volume Não Entregue    1662 non-null   int64
 6   Hora da Entrega        1662 non-null   object
 7   ID Entregador          1662 non-null   object
 8   Nome Motorista         1662 non-null   object
 9   Idade Motorista        1662 non-null   int64
 10  Viagens                1662 non-null   int64
 11  ID Consumidor          1662 non-null   object
 12  Nome Clinte            1662 non-null   object
 13  Idade Cliente          1662 non-null   int64
 14  product_id             1662 non-null   object
 15  Nome Produto           1662 non-null   object
 16  Categoria              1662 non-null   object
 17  Preco                  1662 non-null   float64
dtypes: float64(2), int64(5), object(11)
memory usage: 246.7+ KB